add gsoc-2023-eclipse-gradle-kotlin
KotlinFoundation/kotlinfoundation.github.io pull request #51
Opened 2023-12-15 22:50 UTC by jamesward

2023-12-18 11:26 UTC, zoobestik commented
@koshachy, could you proofread please?

2023-12-18 11:54 UTC, zoobestik requested changes

2023-12-18 11:54 UTC, zoobestik commented on src/pages/news/gsoc-2023-eclipse-gradle-kotlin/index.md
> +**Hovering***
```suggestion
**Hovering**
```

2023-12-18 11:54 UTC, zoobestik commented on src/pages/news/gsoc-2023-eclipse-gradle-kotlin/index.md
> +![Go-to-definition](image4.gif)
There is support only `jpg`, `png`, `webp`, `tiff`, `avif` formats 😞
Is it possible to get better quality image in this place?
<img width="345" alt="Screenshot 2023-12-18 at 12 50 27" src="https://github.com/KotlinFoundation/kotlinfoundation.github.io/assets/242514/c3b35b3d-d873-4310-a572-8b12112b9605">

2024-01-03 15:13 UTC, koshachy approved these changes
Hey there, 
Sorry for the delay. I've slightly updated the markup of the page.
Hope you don't mind.
Ping me if you have any questions.
Thanks!

2024-01-03 18:25 UTC, jamesward commented
Thanks! What are the next steps for getting this published?

2024-01-04 10:53 UTC, zoobestik commented
@jamesward рi, I'm still having an issue with the animated GIF. ⚠️
I'll fix it today, and it will be done.

2024-01-04 15:55 UTC, jamesward commented
That is odd about the GIF as it should work like any other image.  But I haven't tried running the Gatsby server to check it.  Is that where you are seeing the problem?

2024-01-05 13:43 UTC, zoobestik approved these changes

2024-01-05 13:48 UTC, merged

2024-01-05 19:45 UTC, jamesward commented
Thank you! And thanks for working through getting that GIF working!